### PR TITLE
Support bionic and jammy

### PR DESCRIPTION
**Pull request by fejnartal**
[#181711707]

Followed several suggestions found in PR #16

### CODE REVIEW

**Comment by amhuber** [comment]
I haven't actually tested this yet, but taking a quick look at the packages you grabbed I see a couple of issues:

- You appear to have grabbed the package from the "bionic" repo instead of "bionic-updates", so you've got an older package than what I've got on an updated system (1.5.9-9.2ubuntu2 vs. 1.5.9-9.2ubuntu2.1).  The current package is at https://packages.ubuntu.com/bionic-updates/keyutils.
- The keyutils package depends on libkeyutils1 which you aren't installing, and I'm fairly certain it won't actually work without the library.  You'll need to include https://packages.ubuntu.com/bionic-updates/libkeyutils1 and https://packages.ubuntu.com/jammy/libkeyutils1 as well.

Here is what I see on a bionic stemcell after running apt-get install keyutils for example:

    dpkg --list | grep keyutils
    ii  keyutils                              1.5.9-9.2ubuntu2.1                              amd64        Linux Key Management Utilities
    ii  libkeyutils1:amd64                    1.5.9-9.2ubuntu2                                amd64        Linux Key Management Utilities (library)

**Comment by fejnartal** [comment]
> I haven't actually tested this yet, but taking a quick look at the packages you grabbed I see a couple of issues:
> 
> * You appear to have grabbed the package from the "bionic" repo instead of "bionic-updates", so you've got an older package than what I've got on an updated system (1.5.9-9.2ubuntu2 vs. 1.5.9-9.2ubuntu2.1).  The current package is at https://packages.ubuntu.com/bionic-updates/keyutils.
> * The keyutils package depends on libkeyutils1 which you aren't installing, and I'm fairly certain it won't actually work without the library.  You'll need to include https://packages.ubuntu.com/bionic-updates/libkeyutils1 and https://packages.ubuntu.com/jammy/libkeyutils1 as well.
> 
> Here is what I see on a bionic stemcell after running apt-get install keyutils for example:
> 
> ```
> dpkg --list | grep keyutils
> ii  keyutils                              1.5.9-9.2ubuntu2.1                              amd64        Linux Key Management Utilities
> ii  libkeyutils1:amd64                    1.5.9-9.2ubuntu2                                amd64        Linux Key Management Utilities (library)
> ```

Hello. @amhuber thank you for your feedback.
If you could have a go and test it that would be great.

### Regarding libkeyutils depedency:
We have tested the installation of the deb package without issues (dpkg didn't complain).
This could be explained by the "libkeyutils" package being installed in Bionic stemcell by default,
or by some other script or process running apt-get and forcing the installation of missing dependencies.

### Regarding not up-to-date keyutils:
We have included the same version included in [this nfs-volume-release PR](https://github.com/cloudfoundry/nfs-volume-release/pull/72/files).
Automating dependency bumps for these blobs is in our roadmap. However we are not there yet, so we have to do this kind of bumping manually.

I'm have created a [story in tracker for bumping keyutils both in nfs-volume-release and smb-volume-release](https://www.pivotaltracker.com/story/show/181919629) to latest version 1.5.9-9.2ubuntu2.1 using https://mirrors.edge.kernel.org/ubuntu/pool/main/k/keyutils/

**Comment by amhuber** [comment]
Yes, the smbdriver is definitely broken if libkeyutils1 is not present.  I tried the new version that installs just keyutils and the volume failed to mount:

    2022-04-18T11:44:38.30-0700 [API/2] OUT App instance exited with guid f1adff4f-9d67-4ee0-a98a-8dc12458108d payload: {"instance"=>"de08cf7f-8f6d-4a7a-6f36-2b39", "index"=>0, "cell_id"=>"c68cb314-9d0c-4fcc-a2f2-c8127d4f66a0", "reason"=>"CRASHED", "exit_description"=>"failed to mount volume, errors: exit status 32", "crash_count"=>1, "crash_timestamp"=>1650307478168907379, "version"=>"1d3f64be-0908-466e-b8c4-8f335571833b"}

I then manually installed libkeyutils1 and it started working immediately.

**Comment by amhuber** [comment]
Just FYI, dpkg will never complain if you install a single DEB package without it's dependencies, as it's usually up to APT to manage the dependencies.  It will however complain if you try to remove one:

    dpkg --remove libkeyutils1
    dpkg: dependency problems prevent removal of libkeyutils1:amd64:
     libkrb5-3:amd64 depends on libkeyutils1 (>= 1.5.9).
     keyutils depends on libkeyutils1 (>= 1.5.9).
    
    dpkg: error processing package libkeyutils1:amd64 (--remove):
     dependency problems - not removing
    Errors were encountered while processing:
     libkeyutils1:amd64

**Comment by amhuber** [comment]
Sorry, I think I was incorrect, I was doing testing on an image that we were still manually updating to get around the issue previously, libkeyutils1 is present in the stemcell by default.  I'll do a full test with a clean stemcell using the new release and confirm it is working.

**Comment by amhuber** [comment]
I can confirm the new release does work correctly on a non-modified stemcell, sorry for the confusion.

**Comment by fejnartal** [comment]
Thanks @amhuber for your really valuable insights and feedback

**Pull request merged**
