### PR TITLE
Tile version 1.0.0/1.1.0/1.1.1

### PR DESCRIPTION
**Pull request by HDYA**

### CODE REVIEW

**Comment by DennisDenuto** [comment]
Hi @HDYA 

Thanks for this pull request.  We'd like to gain a better understanding of your intention for the SMB Volume Service PCF Tile so that we can figure out what to do with these changes.

Unfortunately we are not going to merge this PR into the master branch. This repository is responsible for the packaging of a bosh release, which may be used in a PCF tile. (The `PAS` tile and also the `SMB Volume Service for PCF` are such examples). 

The PCF tile configuration is a separate component and should live in its own repository. 

We are planning on removing the [tile.yml](https://github.com/cloudfoundry/smb-volume-release/blob/master/pcf-tile/tile.yml) from this repository. We would like to work with you on migrating this to its own repository.

Does Microsoft plan to continue supporting the SMB tile?  

If so, then we propose to:
- remove the driver add-on from the tile, and just package the broker.  
- move the tile assets into a separate repository, since the broker will not need to correspond to a specific smb-volume-release version. 

We are happy to work with you on these changes, and to create a new repository in the Cloud Foundry org to house the tile assets.  

Please let us know your thoughts.

**Comment by julian-hj** [comment]
closing this due to inactivity--please let us know if you'd like to collaborate on a new tile version though!

**Comment by HDYA** [comment]
Hi @DennisDenuto ,

Sorry for missing notification for this PR,
I think we have asked Pivotal to take over SMB tile several months ago.

We'll have a discussion on your proposal and come back to you soon.

Thanks

**Comment by DennisDenuto** [comment]
@HDYA 

I don't think this has been communicated to our team (`CF Volume Services`) that owns/maintains this repo. Also this team belongs to the CloudFoundry foundation, and is not solely a 'Pivotal' team.

Who did you talk to in regards to taking ownership of the 'Microsoft Azure File service'

**Comment by DennisDenuto** [comment]
I am going to close this GH PR again. This isn't a product that the team is at this time willing to support.

**Pull request closed without merging**
